AWSTemplateFormatVersion: "2010-09-09"
Description: Set up DNS records for the ELB.

Parameters:
  Environment:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - production
    Description: The environment for which the Route 53 records needs to be created.

  DNSName:
    Type: String
    Description: The URL of the load balancer to deploy.

  PrimaryDomainName:
    Type: String
    Description: Name of the domain to add A records to, as defined in the hosted zone

  DomainName:
    Type: String
    Description: The URL of the domain to apply the change to.

  HostedZoneId:
    Type: String
    Description: The ID of the hosted zone

Outputs:
  DomainName:
    Value: !Ref DomainName
    Export:
      Name: !Sub "DomainName-${Environment}"

Conditions:
  NeverTrue:
    Fn::Equals: [ 'true', 'false' ]

Resources:
  NullResource:
    Type: 'Custom::NullResource'
    Condition: NeverTrue
