{{- if .Values.service.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ template "appname" . }}
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version| replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    sandboxId: "{{ .Values.biomageCi.sandboxId }}"

  annotations:
{{- if .Values.ingress.tls.enabled }}
    alb.ingress.kubernetes.io/actions.ssl-redirect: >-
      {"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port":
      "443", "StatusCode": "HTTP_301"}}
    alb.ingress.kubernetes.io/certificate-arn: >-
      {{ .Values.myAccount.acmCertificate }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
{{- end }}
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/success-codes: {{ default .Values.loadBalancerHealthCheck.successCodes .Values.ingress.annotations.loadBalancerHealthCheck.successCodes }}
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: {{ default .Values.loadBalancerHealthCheck.periodSeconds .Values.ingress.annotations.loadBalancerHealthCheck.periodSeconds }}
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: {{ default .Values.loadBalancerHealthCheck.timeoutSeconds .Values.ingress.annotations.loadBalancerHealthCheck.timeoutSeconds }}
    alb.ingress.kubernetes.io/healthcheck-protocol: {{ default .Values.loadBalancerHealthCheck.scheme .Values.ingress.annotations.loadBalancerHealthCheck.scheme }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ default .Values.loadBalancerHealthCheck.path .Values.ingress.annotations.loadBalancerHealthCheck.path }}
    alb.ingress.kubernetes.io/healthy-threshold-count: {{ default .Values.loadBalancerHealthCheck.successThreshold .Values.ingress.annotations.loadBalancerHealthCheck.successThreshold }}
    alb.ingress.kubernetes.io/unhealthy-threshold-count: {{ default .Values.loadBalancerHealthCheck.failureThreshold .Values.ingress.annotations.loadBalancerHealthCheck.failureThreshold }}
    alb.ingress.kubernetes.io/group.name: {{ .Values.kubernetes.env }}
spec:
  rules:
  - host: {{ template "hostname" . }}
    http:
      &httpRule
      paths:
{{- if .Values.ingress.tls.enabled }}
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
{{- end }}
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ template "appname" . }}
            port:
              number: {{ .Values.service.externalPort }}
{{- if .Values.service.additionalHosts }}
  - host: {{ .Values.myAccount.domainName }}
    http:
      <<: *httpRule
{{- end -}}
{{- end -}}
