# the event export should be deployed only once per cluster, ie. as part of the default sandbox of the api repo
apiVersion: v1
kind: Namespace
metadata:
  name: agi-test-monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agi-test-event-exporter-cfg
  namespace: agi-test-monitoring
data:
  config.yaml: |
    logLevel: info
    logFormat: json
    route:
      match:
        - reason: "BackOff"
          receiver: "cleanup"
      drop:
        - type: "Normal"
    receivers:
      - name: "cleanup"
        sns:
          topicARN: "arn:aws:sns:{{ .Values.myAccount.region }}:{{ .Values.myAccount.accountId }}:work-results-{{ .Values.kubernetes.env }}-default-v2"
          region: {{ .Values.myAccount.region }}
          layout:
            type: kubernetes-event
            reason: {{`{{ .Reason }}`}}
            message: {{`{{ .Message }}`}}
            involvedObject: {{`{{ toJson .InvolvedObject }}`}}
            {{- if (eq 1 2) -}}
            apiUrl: "equal true"
            {{- else -}}
            apiUrl: "equal false"
            {{- end -}}