# the event export should be deployed only once per cluster, ie. as part of the default sandbox of the api repo
# {{ if and (contains "api" .Values.biomageCi.repo) (eq .Values.biomageCi.sandboxId "default") }}
apiVersion: v1
kind: Namespace
metadata:
  name: agi-test-monitoring
---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   namespace: monitoring
#   name: event-exporter
#   annotations:
#     eks.amazonaws.com/role-arn: {{ template "serviceAccountRoleTemplate" .}}/event-exporter-role-{{ .Values.kubernetes.env }}
#     sandboxId: "{{ .Values.biomageCi.sandboxId }}"
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: event-exporter
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: view
# subjects:
#   - kind: ServiceAccount
#     namespace: monitoring
#     name: event-exporter
# ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agi-test-event-exporter-cfg
  namespace: agi-test-monitoring
  # name: event-exporter-cfg
  # namespace: monitoring
data:
# {{ if eq .Values.myAccount.accountId "242905224710" }}
  config.yaml: |
    logLevel: info
    logFormat: json
    route:
      match:
        - reason: "BackOff"
          receiver: "cleanup"
      drop:
        - type: "Normal"
    receivers:
      - name: "cleanup"
        webhook:
          endpoint: https://{{ template "hostname" .}}/v2/kubernetesEvents
          headers:
            User-Agent: kube-event-exporter 1.0
# {{ else }}
  config.yaml: |
    logLevel: info
    logFormat: json
    route:
      match:
        - reason: "BackOff"
          receiver: "cleanup"
      drop:
        - type: "Normal"
    receivers:
      - name: "cleanup"
        sns:
          topicARN: "arn:aws:sns:{{ .Values.myAccount.region }}:{{ .Values.myAccount.accountId }}:work-results-{{ .Values.kubernetes.env }}-default-v2"
          region: {{ .Values.myAccount.region }}
          layout:
            type: kubernetes-event
            reason: "{{ .Reason }}"
            message: "{{ .Message }}"
            involvedObject: "{{ toJson .InvolvedObject }}"
            apiUrl: "api.{{ .Values.myAccount.domainName }}"
# {{ end }}

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: event-exporter
#   namespace: agi-test-monitoring
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: event-exporter
#         version: v1
#     spec:
#       serviceAccountName: event-exporter
#       containers:
#         - name: event-exporter
#           image: ghcr.io/opsgenie/kubernetes-event-exporter:v0.11
#           imagePullPolicy: IfNotPresent
#           args:
#             - -conf=/data/config.yaml
#           volumeMounts:
#             - mountPath: /data
#               name: cfg
#       volumes:
#         - name: cfg
#           configMap:
#             name: event-exporter-cfg
#   selector:
#     matchLabels:
#       app: event-exporter
#       version: v1
# {{ end }}
